### ISSUE TITLE
Comments not saved

### ISSUE THREAD

**Issue by lurkalot** [Underdog-01/SMF-Arcade-RC5#1]
SMF Arcade v2.55 
The comments you enter aren't saved when you finish a game.  But if you click the edit icon on the comment you can enter the comment and it saves.

![smfarc1](https://user-images.githubusercontent.com/6047983/34356555-90fd2b96-ea36-11e7-98ff-c5c8338717f5.png)
![smfarc2](https://user-images.githubusercontent.com/6047983/34356556-913268c4-ea36-11e7-8fee-7e16d8ef1388.png)

**Comment by Underdog-01** [comment]
fixed
ref.
https://github.com/Underdog-01/SMF-Arcade-RC5/commit/38600298450560c19b2103c21449c8df2ba0de69
