### ISSUE TITLE
Images missing from stats

### ISSUE THREAD

**Issue by lurkalot** [Underdog-01/SMF-Arcade-RC5#2]
Images are missing from the arcade stats page. same as here, https://www.docskillz.com/docs/index.php?action=arcade;sa=stats and here, https://web-develop.ca/index.php?action=arcade;sa=stats

**Comment by Underdog-01** [comment]
fixed:
https://github.com/Underdog-01/SMF-Arcade-RC5/commit/1a425705a5f552ef4f03b8b5a44d3489afbbbd74
