### ISSUE TITLE
Errors in log

### ISSUE THREAD

**Issue by lurkalot** [Underdog-01/SMF-Arcade-RC5#3]
SMF Arcade v2.55 Downloaded from here, https://www.docskillz.com/docs/index.php?topic=1311.0

These errors in SMF error log.

Type of error: Undefined  
http://localhost/smf2014/index.php?action=arcade;sa=highscore;xml;
8: Undefined index: comment
File: C:/xampp/htdocs/smf2014/Sources/Subs-ArcadePlus.php
Line: 848 

Type of error: Undefined  
http://localhost/smf2014/index.php?action=arcade;sa=highscore;xml;
8: Undefined index: comment
File: C:/xampp/htdocs/smf2014/Sources/Subs-ArcadePlus.php
Line: 848  

Type of error: General  
http://localhost/smf2014/index.php?action=admin;area=managegames;sa=install2;sesc
2: Invalid argument supplied for foreach()
File: C:/xampp/htdocs/smf2014/Sources/Subs-ArcadeAdmin.php
Line: 392  

Type of error: Undefined  
http://localhost/smf2014/index.php?action=admin;area=managegames;sa=install2;sesc
8: Undefined variable: masterGameinfo
File: C:/xampp/htdocs/smf2014/Sources/Subs-ArcadeAdmin.php
Line: 392

**Comment by Underdog-01** [comment]
The last 2 errors reported were fixed here:
https://github.com/Underdog-01/SMF-Arcade-RC5/commit/c32d141b6a01b1054d9941a8f92a41285184d96f

Thus far I have not been able to duplicate the undefined errors reported here.

**Comment by Underdog-01** [comment]
The undefined errors reported as no longer showing in the logs.
ref.
https://www.docskillz.com/docs/index.php?topic=1311.msg6180#msg6180

Due to that report I am closing this issue report.
